version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: forohub
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
